apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  type: LoadBalancer
  selector:
    service: analytics-api
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-api
  labels:
    name: analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: analytics-api
  template:
    metadata:
      labels:
        service: analytics-api
    spec:
      containers:
      - name: analytics-api
        image: 549257863378.dkr.ecr.us-east-1.amazonaws.com/coworking-space/analytics-api:v0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 15
        envFrom:
        - configMapRef:
            name: db-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
      restartPolicy: Always